import { getComponents } from "@/database/templates/components";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LayoutProvider from "../providers/layoutProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ecoms.ai Templates Builder",
  description: "Generated by ecoms.ai",
};


export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  console.log("inside layout")
  const templatesList = await getComponents();
  console.log("templatesList fetched inside layout root")

  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutProvider templatesList={templatesList} >{children}</LayoutProvider>
      </body>
    </html>
  );
}
